# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0002_mongouser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MongoUser',
            new_name='SmartsharkUser',
        ),
    ]
