# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import smartshark.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0006_auto_20160607_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='zip',
            field=models.FileField(default=None, upload_to='uploads/', validators=[smartshark.models.FileValidator(content_types=('application/x-tar', 'application/zip'), max_size=52428800)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plugin',
            name='definition',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='schema',
            field=models.FileField(upload_to=''),
        ),
    ]
