# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0009_auto_20160608_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='arguments',
        ),
        migrations.AddField(
            model_name='argument',
            name='plugin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smartshark.Plugin'),
            preserve_default=False,
        ),
    ]
