# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0010_auto_20160608_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
