# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0011_auto_20160608_1414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together=set([('name', 'version')]),
        ),
    ]
