# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0012_auto_20160608_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clone_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
