# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0014_auto_20160609_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginexecution',
            name='job_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pluginexecution',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Requirements'), ('queue', 'In Queue'), ('running', 'Running'), ('finished', 'Finished'), ('error', 'Error')], max_length=8),
        ),
    ]
