# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0016_auto_20160610_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
