# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0018_auto_20160616_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'permissions': (('install_plugin', 'Permission to install plugins.'),)},
        ),
    ]
