# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0026_auto_20160630_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('EXIT', 'Exit'), ('WAIT', 'Waiting')], max_length=8),
        ),
    ]
