# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0027_auto_20160725_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='value',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
