# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0028_argument_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
