# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-27 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0029_auto_20161027_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='value',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
