# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0032_auto_20161028_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='error_log',
        ),
        migrations.RemoveField(
            model_name='job',
            name='output_log',
        ),
        migrations.RemoveField(
            model_name='job',
            name='revision_path',
        ),
        migrations.RemoveField(
            model_name='job',
            name='submission_string',
        ),
        migrations.AddField(
            model_name='job',
            name='requires',
            field=models.ManyToManyField(blank=True, to='smartshark.Job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='revision_hash',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('EXIT', 'Exit'), ('WAIT', 'Waiting')], default='WAIT', max_length=8),
        ),
    ]
