# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-01 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0033_auto_20161101_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='clone_username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
