# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-04 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0035_auto_20161214_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginexecution',
            name='cores_per_job',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pluginexecution',
            name='queue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginexecution',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('EXIT', 'Exit'), ('WAIT', 'Waiting')], default='WAIT', max_length=8),
        ),
    ]
