# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0036_auto_20181104_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
