# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-08-23 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0036_mongoexecutionreader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mongoexecutionreader',
            name='project',
        ),
        migrations.CreateModel(
            name='ProjectMongo',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('smartshark.project',),
        ),
        migrations.DeleteModel(
            name='MongoExecutionReader',
        ),
    ]
