# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0037_auto_20181120_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcs_system', models.CharField(max_length=100)),
                ('commit', models.CharField(max_length=250)),
                ('vcsSHARK', models.BooleanField()),
                ('mecoSHARK', models.BooleanField()),
                ('coastSHARK', models.BooleanField()),
                ('text', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartshark.Project')),
            ],
        ),
    ]
