# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0038_project_executions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datacounts',
            field=models.TextField(default='None', editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='projectmap',
            field=models.TextField(default='None', editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='executions',
            field=models.TextField(default='None', editable=False),
        ),
    ]
