# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-17 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0039_auto_20180910_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='datacounts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectmap',
        ),
    ]
