# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-10-15 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import smartshark.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0041_auto_20181009_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmongo',
            name='executed_plugins',
        ),
        migrations.AddField(
            model_name='projectmongo',
            name='executed_plugins',
            field=models.TextField(blank=True, editable=False, verbose_name=smartshark.models.Plugin),
        ),
        migrations.AlterField(
            model_name='projectmongo',
            name='issue_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectmongo',
            name='mailing_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectmongo',
            name='validation',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectmongo',
            name='vcs_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
