# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-02 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0041_auto_20181102_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmongo',
            name='last_validation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
