# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-09 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0042_auto_20181102_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_hash', models.CharField(default='None', max_length=50)),
                ('valid', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartshark.ProjectMongo')),
            ],
        ),
    ]
