# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-09 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0043_commitvalidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commitvalidation',
            old_name='project',
            new_name='projectmongo',
        ),
    ]
