# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-13 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartshark', '0044_auto_20181109_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitvalidation',
            name='coast_missing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commitvalidation',
            name='coast_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commitvalidation',
            name='meco_missing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commitvalidation',
            name='meco_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmongo',
            name='meco_validation',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
